"""Create User model

Revision ID: f2e35847300a
Revises: 8a1d475bb935
Create Date: 2025-08-05 14:31:37.466899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2e35847300a'
down_revision: Union[str, Sequence[str], None] = '8a1d475bb935'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=False)
    # ### end Alembic commands ###
